### ISSUE TITLE
Gitlab - Failing test

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/topcoder-x-processor#11]
From the recent review:

> For "tests for closing a gitlab ticket - no assigne exists" to "ensures a comment is added to the Gitlab ticket and the ticket is reopened"In IssueService.handleIssueClose method, line 408, it will re-open issue and make comment , I think that's the case you need to test.

**Comment by MayurRJoshi** [comment]
The recommended test path, _IssueService.handleIssueClose method, line 408_
```
// no mapping is found for current assignee remove assign, re-open issue and make comment
// to assignee to login with Topcoder X
   if (!(assigneeMember && assigneeMember.topcoderUsername)) {
     await rollbackAssignee(event, event.data.assignee.id, issue, true);
   }
```
tests closing an issue when an **assignee exists** but is not registered with topcoder and hence does not have a mapping.
_tests for closing a gitlab ticket - **no assigne exists**_ should test  _IssueService.handleIssueClose method, line 394_ which currently does nothing
```
// if issue is closed without assignee then do nothing
if (!event.data.assignee.id) {
     logger.debug(`This issue ${issue.number} doesn't have assignee so ignoring this event.`);
     return;
   }
```
The test requirement states, _Close a Github ticket - If there's no assignee, ensure a comment is added to the Github ticket and the ticket is reopened_.
So I think the existing test is correct in failing.

**Comment by jmgasper** [comment]
Yep, feel free to document that in your README.
