### ISSUE TITLE
Retry Queuing locks ticket in infinite loop

### ISSUE THREAD

**Issue by cwdcwd** [topcoder-platform/topcoder-x-processor#13]
When creating issues in Github or Gitlab it seems that failures to parse the ticket title cause the processing of the ticket to requeue. This puts the `status` field on the mongo record to `challenge_creation_pending`. Once that's set nothing gets updated. The only solution has been to:
- clear any assignees
- clear any TCX labels
- delete the record
- wait for the processor to catch up
- reset the Open for Pickup label

after that everything seems to work. The only thing I've been able to tease out of the logs is a failure to parse the title prizes. Often existing or new bugs come in without prizes set before a ticket is opened and I think that might be a root cause.

**Comment by veshu** [comment]
@jmgasper Yes if issue doesn't reque if prize is [] or [$] or no [] in the title.
Without valid prize no event passes to the respective handler.

There must be some different situation that is causing this.

**Comment by jmgasper** [comment]
@veshu  - Please have a look at this one too, for context.  Basically we don't think retrying *ever* works correctly:  https://github.com/topcoder-platform/topcoder-x-ui/issues/93
